language: java
jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
 - chmod +x gradlew

after_success:
  - .buildscript/deploy-snapshot.sh

notifications:
  email: true

env:
  global:
    - secure: "jCwdWzaaQpZYuwkW8B2uuxNJK8cz9CgEfFU6+TKpZhPAXncPUZE/CQAxa6jMK6t+PwB0bUzCtE7b0GVWlKNRRG2qr21VeOqCZ85nd8aajcm0hAQ6cmpiKO9TKX3BRLsAs7jgz6pBIS3UPaMUjl5/YK/ORpU/Oo+FekbK/+UE0kG0Q6Rv+nA+LRP3zfp3nacvSz+lYnjyt5H+ZzFs9v/y5Jc95KpefVGeQVZL6kRRzSHu45e3jRi3FPhBKs/GY3E9h303Mof6b2RYJ38vzWCwun+DZfGT1KhW0O3gBd3m7Tty7Mz4VBxZrkCS0kpSNHBNxfjv/N6Td+YU3e6PbomABP/IZADQS1hatl6wrPCQ6bV2FXDSSxSaTOkv30xat6XKSSxtYn85D8vpFHWaoIY1woooaVSMgOpdWwcxivuQwbsWw9fHLNC9Dk1d7O2rG9Tui13vj5SNPIhwBdSU9Fxqo180ANn/IXGOUNGKvp1IG/gak+ZMEI059HaKijJzJt/ZWzY/T4Cu42PRBnVi6TeD8xkC5DnQ79wnxMF1oCCbtaD8pu4wJKXRTW2PJ/tOq5P7jXSnYcnlrh6+G91WQYHylTYIFHRRBPUwwOsCmXv1kyMdu7otJpJcPywNFOR0MxGIUcxpB2vcxN2C13K17mgHqUTvHG8rpEWiWaBI7mTMkdA="
    - secure: "ZOo6ahFQmozGpXFHfQ+ZWT450p5Pf/88IYTkK+NFe8Vb3lPFMPwWI3caSmFoykWWu656uKBMNud03bjUEQ6fy29Y5rW/PXNWTqtich7jgjqTv3+Om/PR+6Dk8REWa+Yg/uKdjq6HYRyoOstoqTLkWzIbT/lvJCgAv59K2HL7MzhG++UBnZ4zKjz6YOc2jXBXhBn6lNCkaSy3FatKXeNJGyy2HoQU/guH8K7qjK6XkhrAElnQ+FcoebIISgKOX4I6v6CqrJUUz9sOa1BIZlLsItBDizI0YAj1jJlRUp4BZRglOJq/9FnRHtdRwjLRKeW4CdaO4HapTs+XaYiFi0ZPe0susuPxCSSgRp8l17ZJAFfE22ob2HZ8WAdUntBHsqCDMRq5koZvelon+E0JFdCT+pimNvV9hsx+QrvDtjcqQqJZEdoVSl+/P0BOELxNPcQOsQjirMFp3LpC8jqss3ZVZKPAOG2qrvIbUy1fcfXaqxrUO2nD5FqBKRLjOMZZO1uqzYaNlyw5d/I1P0JjIIUWoiynufWe3boNIacmQo2gozofbe8G1ja9vxaQyrYd4ZAPrNKyGzi68uGFDLmiJhhDktRyda3ZfqbeUnwzT57PlUysyImYeUDy6MULj2HoVn7VgYzvC3ctCYJNidkcEOTg7twegVUhDnt+Ma+a5e5iGbs="

sudo: false

cache:
  directories:
    - $HOME/.gradle